name: drishya_picker
description: Messenger like image, video picker with two different option. 1. Using Controller 2. Using MediaPicker widget
version: 1.0.0+1
homepage: https://github.com/koiralapankajgit/drishya_picker

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  photo_manager: ^1.1.0
  camera: ^0.8.1
  video_player: ^2.1.1
  image_picker: ^0.7.4
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
