name: drishya_picker
description: Messenger like image, video picker with two different option. 1. Using Controller 2. Using MediaPicker widget
version: 1.0.0+1
homepage: https://github.com/koiralapankajgit/drishya_picker

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  photo_manager: ^1.2.2
  camera: ^0.8.1+3
  image: ^3.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.1.2

flutter:
  uses-material-design: true

  assets:
    - lib/assets/camera.png

  fonts:
    - family: CustomIcons
      fonts: 
        - asset: lib/assets/fonts/CustomIcons.ttf
  